version: '3.8'

services:
  item-app:
    image: ghcr.io/alexzpurewoko/item-app-project-alexzforger:v1
    depends_on:
      - item-db
    ports:
      - "80:8080"
    deploy: 
      restart_policy:
        condition: any
        delay: 3s
        window: 30s
    
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db 

volumes:
  app-db: