version: '3.8'

services:
  item-app:
    image: alexzpurewoko/item-app-project-alexzforger:v1
    restart: on-failure
    depends_on:
      - item-db
    ports:
      - "80:8080"
    
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db 

volumes:
  app-db: